Pcs 137
Pet-Care-Services/PCS-Backend pull request #42
Opened 2022-09-23 21:33 UTC by lstachon

2022-10-03 15:16 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/dto/DtoPin.java
> +    int radius;
w jakiej jednostce będzie radius ?
Bo jeśli to są metry to chyba git, ale jeśli kilometry to pewnie lepiej zeby to byl float

2022-10-03 15:18 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/model/location/DbLocation.java
> +    private String postalCode;
przydałby sie jakis contraint ze musi miec 5 cyfr

2022-10-03 15:30 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/advertisementservice/ServiceAdvertisementService.java
> +
Wydaje mi sie ze ostatecznie to miało byc pojedyncze miejsce a nie lista. Ale jeśliby to miało zostać tak jak jest teraz to wydaje mi sie ze i tak trzebaby lokalizacje i piny przysylac jako mape, bo inaczej nie wiadomo jak są ze sobą powiązane

2022-10-03 15:32 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/location/LocationService.java
> +}
Tu nie powinno byc jakjies implementacj dodawania ?

2022-10-03 15:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/request/RequestService.java
> +                new DtoLocation(v.getLocation().getCity(), v.getLocation().getPostalCode(), v.getLocation().getAddress(), v.getLocation().getFlatNumber())
Takie konwersje lepiej by było robić przez mapper

2022-10-03 16:00 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/service/ServiceService.java
> +        userRepository.save(user);
Nie trzeba zapisać osobno samej lokalizacji ?

2022-10-03 16:05 UTC, StencelMichal requested changes
Jest pare rzeczy do zmiany, ale ogólnie wygląda że jest git. Zastanawiam się jeszcze na tą nazwą `Pin`, czy nie lepsza byłaby nazwa `Coord` albo coś w tym rodzaju, ale to już jak wolisz.

2022-10-05 17:43 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/dto/DtoPin.java
> +    int radius;
raczej w metrach ale trzeba sprawdzić w jakich jednostkach api przyjmuje

2022-10-06 17:25 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/model/location/DbLocation.java
> +    private String postalCode;
Nw jak to jest robione na froncie, ale jeśli tam nie ma walidacji żeby zawsze wysyłać w formacie XX-XXX to robi się to troche włochate. Wypadałoby zrobić do tego klaske `PostalCode` i później zapisywać ją do bazy jako string 5 cyfr, albo zdefiniować customowy typ w bazie

2022-10-06 17:26 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/model/location/DbLocation.java
> +    private String postalCode;
moim zdaniem najlepiej będzie zrobić walidacje na froncie i zapisywać jako XX-XXX bo nie ma sensu tego utrudniać dodatkowo

2022-10-06 17:30 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/model/location/DbLocation.java
> +    private String postalCode;
W praktyce to i tak powinno być otypowane, ale jak to dogadasz z @mskwara to można zostawić

2022-10-08 09:41 UTC, StencelMichal approved these changes

2022-10-08 09:41 UTC, merged