Pcs 155
Pet-Care-Services/PCS-Backend pull request #52
Opened 2022-11-06 22:31 UTC by lstachon

2022-11-09 19:37 UTC, StencelMichal requested changes

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/model/message/DbMessageOffer.java
> +
Mozna tutaj wsadzic price type, nie trzeba wtedy sprawdzac w serwisie czy nalezy do seriwsu czy requestu i to mapowac

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/model/message/DbMessage.java
> +
Troche dziwny jest dla mnie ten model, zeby wrzucac offer do message. Bo w DTO czasem wrzucamy offer do message a czasem message do offer, a jeden nie korzysta z pól drugiego. Tzn jesli mamy offer to nie potrzebujemy text, a jak message to nie musimy miec informacji z offer. Wydaje mi się, ze to rozwiazanie wzielo sie z checi reuzycia pol takich jak `userFrom`, `userTo`, `conversation`. Lepiej byloby jednak rozdzielic te dwie encje, bo pozniej w kodzie sa niepotrzebne ify i sprawdzanie typow, poniewaz w praktyce probojemy za pomoca jednej encji modelowac dwie. Mozna stworzyc jakas abstrakycjna klase `Message` i przeniesc tam wspolne pola oraz stworzyc dwie implementacje w stylu `TextMessage` i `OfferMessage`. W takim rozwiazaniu logika jest prostsza i jedynie nalezy pamietac, zeby przy zwracaniu wszystkich wiadomosci, pobrac z obu repozytoriow wiadomosci i zwrocic jako "konwersacje" = List<Message>

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/message/MessageService.java
> +        }
warto rzucic jakis wyjatek

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/message/MessageService.java
> +    }
pewnie lepiej sprawdzic czy cos tam jest i ewentualnie rzucic wyjatek

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/service/ServiceService.java
>      }
wyjatek jesli nie bedzie w bazie

2022-11-09 19:37 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/request/RequestService.java
> +
wyjatek jesli nie ma w bazie

2022-11-12 22:07 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/service/ServiceService.java
>      }
jak wyżej

2022-11-12 22:07 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/message/MessageService.java
> +    }
po co skoro spring sam to obsługuje? 
<img width="1251" alt="Screenshot 2022-11-12 at 23 06 52" src="https://user-images.githubusercontent.com/64076091/201496391-c69a13da-1e44-4c9d-98a8-bec99f73676a.png">

2022-11-12 22:07 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/request/RequestService.java
> +
jak wyżej

2022-11-12 22:08 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/model/message/DbMessage.java
> +
tak jak obgadaliśmy na spotkaniu, nie ma sensu tego przekombinowywać przy aktualnych zasobach czasowych.

2022-11-12 22:15 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/message/MessageService.java
> +    }
po co skoro spring to sam robi i prawdopodobnie nie chcemy rzucać innego wyjątku niż default?
<img width="1345" alt="Screenshot 2022-11-12 at 23 14 38" src="https://user-images.githubusercontent.com/64076091/201496623-3049abf9-a49e-443a-962d-eafc04b53101.png">

2022-11-12 22:16 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/service/ServiceService.java
>      }
to nie będzie używane bo wywaliliśmy pobieranie serwisu i requestu ale można zostawić bo to takie uniwersalne metodki, ale tak jak pisałem wyżej nie trzeba tu nic obsługiwać

2022-11-12 22:16 UTC, lstachon commented on src/main/java/com/pcs/petcareservices/service/request/RequestService.java
> +
jak wyżej

2022-11-12 22:18 UTC, StencelMichal commented on src/main/java/com/pcs/petcareservices/service/message/MessageService.java
> +    }
Okej, gituwa

2022-11-12 22:18 UTC, StencelMichal approved these changes

2022-11-13 10:49 UTC, merged